# Generated by Django 2.2.16 on 2020-10-07 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_merge_20201005_2253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-date'], 'verbose_name': 'Activité'},
        ),
        migrations.AlterField(
            model_name='localsettings',
            name='mail_protocole',
            field=models.CharField(choices=[('no', 'Pas de chiffrement'), ('tls', 'Utiliser TLS'), ('ssl', 'Utiliser SSL')], default='no', max_length=100, verbose_name="Chiffrement utilisé pour l'envoi de mails."),
        ),
        migrations.AlterField(
            model_name='localsettings',
            name='prefix_object_mail',
            field=models.CharField(blank=True, default='', help_text='Un préfixe est souvent encadré par des crochers, exemples : [GASE].', max_length=15, verbose_name="Préfixe dans l'objet des emails."),
        ),
    ]
