# Generated by Django 2.2.27 on 2022-03-30 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_auto_20220206_2325'),
        ('base', '0020_auto_20201007_2121'),
    ]

    operations = [
    ]
